application: comic-pull-db
version: live
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/pulldb.png
  upload: static/pulldb.png
- url: /admin($|/.*)
  script: pulldb.admin.app
  login: admin
- url: /issues($|/.*)
  script: pulldb.issues.app
  login: required
- url: /subscriptions($|/.*)
  script: pulldb.subscriptions.app
  login: required
- url: /users($|/.*)
  script: pulldb.users.app
  login: required
- url: /volumes($|/.*)
  script: pulldb.volumes.app
  login: required
- url: /
  script: pulldb.index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
