application: comic-pull-db
version: rgh
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/pulldb.png
  upload: static/pulldb.png
- url: /admin($|/.*)
  script: pulldb.admin.app
  login: admin
- url: /issues($|/.*)
  script: pulldb.issues.app
  login: required
- url: /tasks/issues/.*
  script: pulldb.api.issues.app
  login: admin
- url: /api/issues/.*
  script: pulldb.api.issues.app
- url: /api/pulls/.*
  script: pulldb.api.pulls.app
- url: /subscriptions($|/.*)
  script: pulldb.subscriptions.app
  login: required
- url: /api/subscriptions/.*
  script: pulldb.api.subscriptions.app
- url: /tasks/subscriptions/.*
  script: pulldb.api.subscriptions.app
  login: admin
- url: /users($|/.*)
  script: pulldb.users.app
  login: required
- url: /volumes($|/.*)
  script: pulldb.volumes.app
  login: required
- url: /tasks/volumes/.*
  script: pulldb.api.volumes.app
  login: admin
- url: /api/volumes/.*
  script: pulldb.api.volumes.app
- url: /
  script: pulldb.index.app

builtins:
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
